version: '3.3'
networks:
  teste-network:
    driver: bridge
services:
  dbMysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    container_name: sysmsgm
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: msg   
    networks:
      - teste-network

  phpmyadmin:
    image: phpmyadmin
    ports:
       - 8085:80
    environment:
      - PMA_ARBITRARY=1
    links:
      - dbMysql:dbMysql
    networks:
      - teste-network
  
  php:
    image: docker.io/bitnami/laravel:9
    container_name: app_msgm
    ports:
      - '8000:8000'
    volumes:
      - './mensagem:/app'
    depends_on:
      - dbMysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=sysmsgm
      - DB_PORT=3306
      - DB_DATABASE=msg
      - DB_USERNAME=root
      - DB_PASSWORD=password
    links:
      - dbMysql:dbMysql
    networks:
      - teste-network